# Dataset-Specific Profiles for Object Detection
# Auto-filled from deep analysis, enhanced with preprocessing strategies
# Each dataset has its own optimized configuration

datasets:
  # ============================================================================
  # CATTLEBODY - Single object body detection
  # ============================================================================
  cattlebody:
    modality: rgb_camera
    task: single_object_detection

    # Analysis results (from dataset_analysis_results/)
    analysis:
      num_classes: 1
      class_names: ["Cattlebody"]
      format: yolo
      has_data_yaml: true

      # Statistics from analysis
      image_stats:
        mean: [0.5380, 0.5380, 0.5380] # Will be computed from analysis
        std: [0.0820, 0.0820, 0.0820] # Will be computed from analysis
        brightness_mean: 137.20
        contrast_mean: 60.69
        aspect_ratio_range: [0.75, 2.19]

      object_stats:
        objects_per_image: 1.009
        avg_bbox_area: 0.105
        bbox_aspect_ratio: 0.985

      quality_issues:
        - "train: Image/label mismatch (3424 images, 3432 labels)"
        - "Large aspect ratio variation (0.75 to 2.19)"

      recommendations:
        preprocessing:
          - "Resize all images to consistent size (e.g., 640x640)"
          - "Use letterboxing for aspect ratio preservation"
        augmentation:
          - "Horizontal flip (p=0.5)"
          - "Brightness augmentation (±20%)"
          - "Contrast augmentation (±20%)"
          - "Random rotation (±10°)"
          - "Random scale (0.8-1.2)"
          - "Mosaic augmentation"
        training:
          - "Use num_classes=1"
        architecture:
          - "Default anchor sizes work well"

    # Dataset structure
    structure:
      type: "train_val_test"
      raw_path: "dataset/cattlebody"
      processed_path: "processed_data/cattlebody"
      splits:
        train: "train"
        val: "val"
        test: "test"
      split_ratios: null # Already split

    # Preprocessing configuration
    preprocessing:
      enabled: true
      target_size: [640, 640]
      maintain_aspect: true
      letterbox_color: [114, 114, 114] # Gray padding

      # Quality filters
      min_image_size: [320, 320]
      max_image_size: null
      min_bbox_size: 0.001
      filter_invalid_boxes: true
      fix_mismatches: true # Fix train image/label mismatch

      # Normalization
      normalize: true
      normalization:
        method: "imagenet" # or "dataset_specific" to use computed stats
        mean: [0.485, 0.456, 0.406] # ImageNet default
        std: [0.229, 0.224, 0.225]

    # Data augmentation
    augmentation:
      enabled: true
      horizontal_flip: 0.5
      vertical_flip: 0.0
      rotation: 10
      scale: [0.8, 1.2]
      translate: 0.1
      shear: 0.0
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
      mosaic: true
      mixup: 0.0

    # Training configuration
    training:
      epochs: 100
      batch_size: 16
      learning_rate: 0.001
      optimizer: adamw
      loss_type: standard # No class imbalance
      scheduler: cosine
      warmup_epochs: 5
      early_stopping: true
      patience: 20

  # ============================================================================
  # CATTLE - Multi-object detection with class imbalance
  # ============================================================================
  cattle:
    modality: rgb_camera
    task: multi_object_detection

    # Analysis results
    analysis:
      num_classes: 2
      class_names: ["class_0", "class_1"] # Will be auto-detected
      format: unknown
      has_data_yaml: false

      # Statistics
      image_stats:
        mean: [0.4272, 0.4272, 0.4272] # Computed from analysis
        std: [0.1097, 0.1097, 0.1097]
        brightness_mean: 108.96
        contrast_mean: 65.25
        aspect_ratio_range: [0.75, 1.91]

      object_stats:
        objects_per_image: 4.907
        avg_bbox_area: 0.029
        bbox_aspect_ratio: 0.570
        class_imbalance_ratio: 10.40 # SEVERE imbalance!

      quality_issues:
        - "Class imbalance detected (ratio: 10.40)"
        - "Large aspect ratio variation (0.75 to 1.91)"

      recommendations:
        preprocessing:
          - "Resize all images to consistent size"
        augmentation:
          - "All standard augmentations"
          - "Mosaic augmentation for multi-object scenes"
        training:
          - "Use weighted loss or focal loss for class imbalance"
          - "Use num_classes=2"
        architecture:
          - "Use small anchor sizes for tiny objects"
          - "Consider using higher resolution (e.g., 1280x1280)"

    # Dataset structure
    structure:
      type: "train_val_test"
      raw_path: "dataset/cattle"
      processed_path: "processed_data/cattle"
      splits:
        train: "train"
        val: "val"
        test: "test"
      split_ratios: null

    # Preprocessing configuration
    preprocessing:
      enabled: true
      target_size: [1280, 1280] # Higher resolution for small objects
      maintain_aspect: true
      letterbox_color: [114, 114, 114]

      # Quality filters
      min_image_size: [320, 320]
      max_image_size: null
      min_bbox_size: 0.0005 # Smaller threshold for tiny objects
      filter_invalid_boxes: true

      # Normalization
      normalize: true
      normalization:
        method: "dataset_specific" # Use computed stats
        mean: [0.4272, 0.4272, 0.4272]
        std: [0.1097, 0.1097, 0.1097]

    # Data augmentation (aggressive for small objects)
    augmentation:
      enabled: true
      horizontal_flip: 0.5
      vertical_flip: 0.1 # Some vertical variation
      rotation: 15
      scale: [0.7, 1.3] # More scale variation
      translate: 0.15
      shear: 5.0
      brightness: 0.3
      contrast: 0.3
      saturation: 0.3
      hue: 0.15
      mosaic: true
      mixup: 0.15 # Some mixup for multi-object

    # Training configuration
    training:
      epochs: 150 # More epochs due to complexity
      batch_size: 8 # Smaller due to 1280 resolution
      learning_rate: 0.0005 # Lower LR for stability
      optimizer: adamw
      loss_type: focal # Handle class imbalance
      focal_alpha: 0.25
      focal_gamma: 2.0
      scheduler: cosine
      warmup_epochs: 10
      early_stopping: true
      patience: 30

      # Class balancing
      class_balancing: focal_loss
      class_weights: auto # Compute from dataset

  # ============================================================================
  # CATTLEFACE - BROKEN (no labels)
  # ============================================================================
  cattleface:
    modality: rgb_camera
    task: face_detection
    status: broken # Cannot use for training

    # Analysis results
    analysis:
      num_classes: 0
      class_names: []
      format: unknown
      has_data_yaml: false

      quality_issues:
        - "train: Image/label mismatch (4565 images, 0 labels)"
        - "val: Image/label mismatch (979 images, 0 labels)"
        - "test: Image/label mismatch (984 images, 0 labels)"
        - "NO LABELS FOUND - Cannot train!"

      recommendations:
        - "Find original annotation files"
        - "Or re-annotate the dataset"

    # Dataset structure
    structure:
      type: "train_val_test"
      raw_path: "processed_data/cattleface"
      processed_path: null
      splits:
        train: "train"
        val: "val"
        test: "test"

    # Cannot configure preprocessing/training without labels
    preprocessing:
      enabled: false
    training:
      enabled: false

# ============================================================================
# GLOBAL DEFAULTS (fallback if dataset-specific not provided)
# ============================================================================
defaults:
  preprocessing:
    target_size: [640, 640]
    maintain_aspect: true
    letterbox_color: [114, 114, 114]
    min_image_size: [320, 320]
    min_bbox_size: 0.001
    filter_invalid_boxes: true
    normalize: true
    normalization:
      method: "imagenet"
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

  augmentation:
    enabled: true
    horizontal_flip: 0.5
    vertical_flip: 0.0
    rotation: 10
    scale: [0.8, 1.2]
    translate: 0.1
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1
    mosaic: true

  training:
    epochs: 100
    batch_size: 8
    learning_rate: 0.001
    optimizer: adamw
    loss_type: auto
    scheduler: cosine
    warmup_epochs: 5
    early_stopping: true
    patience: 20
