# Quick Experimentation Configuration
# For rapid testing and iteration

# Model Configuration
model: yolov8
# num_classes: Auto-detected from dataset
pretrained: false

# Dataset Configuration
dataset_root: dataset/cattlebody
image_size: 416 # Smaller for faster training
label_format: yolo

# Training Hyperparameters - Fast
epochs: 20
batch_size: 16
learning_rate: 0.001
weight_decay: 0.0001

# Optimizer - Adam for stability
optimizer: adam

# Scheduler - Step LR for simplicity
scheduler: step
scheduler_params:
  step_size: 10
  gamma: 0.1

# Loss Weights
box_weight: 7.5
cls_weight: 0.5
obj_weight: 1.0

# Minimal Augmentation for speed
augment: true
augment_params:
  horizontal_flip: 0.5
  rotation: 5
  brightness: 0.1

# Regularization
dropout: 0.2
gradient_clip: 1.0

# Training Strategy
warmup_epochs: 2
early_stopping: false
mixed_precision: true

# Validation
val_interval: 2
val_metric: mAP

# Checkpointing
save_interval: 10
save_best_only: true

# Output Configuration
output_dir: outputs
experiment_name: yolov8_quick_test
log_interval: 5
save_predictions: false

# Device Configuration
device: cuda
num_workers: 4
pin_memory: true

# Debugging
debug: false
seed: 42
