# YOLOv8 Training Configuration - CattleBody Dataset
# This is a complete example configuration file with zero hardcoding

# Model Configuration
model: yolov8
# num_classes: Auto-detected from dataset
pretrained: false
freeze_backbone: false

# Dataset Configuration
dataset_root: dataset/cattlebody
# The following will be auto-configured from dataset_root:
# train_images: dataset/cattlebody/train/images
# train_labels: dataset/cattlebody/train/labels
# val_images: dataset/cattlebody/val/images
# val_labels: dataset/cattlebody/val/labels

image_size: 640
label_format: yolo

# Training Hyperparameters
epochs: 100
batch_size: 8
learning_rate: 0.001
weight_decay: 0.0001
momentum: 0.9

# Optimizer Configuration
optimizer: adamw
optimizer_params:
  betas: [0.9, 0.999]
  eps: 1.0e-8

# Scheduler Configuration
scheduler: cosine
scheduler_params:
  T_max: 100
  eta_min: 1.0e-6

# Loss Weights
box_weight: 7.5
cls_weight: 0.5
obj_weight: 1.0

# Data Augmentation
augment: true
augment_params:
  horizontal_flip: 0.5
  vertical_flip: 0.0
  rotation: 10
  brightness: 0.2
  contrast: 0.2
  saturation: 0.2
  hue: 0.1

# Regularization
dropout: 0.3
label_smoothing: 0.0
mixup_alpha: 0.0
gradient_clip: 1.0

# Training Strategy
warmup_epochs: 5
early_stopping: true
early_stopping_patience: 20
mixed_precision: true

# Validation
val_interval: 1
val_metric: mAP

# Checkpointing
save_interval: 5
save_best_only: false
checkpoint_dir: null # Will use output_dir/checkpoints

# Output Configuration
output_dir: outputs
experiment_name: yolov8_cattlebody_baseline
log_interval: 10
save_predictions: true

# Device Configuration
device: cuda
num_workers: 4
pin_memory: true

# Debugging
debug: false
profile: false
seed: 42
